### ISSUE TITLE
enable use of custom theme and language

### ISSUE THREAD

**Issue by MalteSchledjewski** [valterkraemer/rollup-plugin-syntax-highlight#1]
For enabling the use of a custom theme, you should reexport `toShikiTheme`.

For enabling a custom language there needs to be a way to call `highlighter.loadLanguage(customLang)` with a custom language.

I hacked this into my [fork](https://github.com/MalteSchledjewski/rollup-plugin-syntax-highlight/tree/custom-theme-and-language) but I am no web dev, and this works for me, but should be solved more elegantly.  

With my own fork I can just use:
``` ts
syntaxHighlight({
      theme: toShikiTheme(VsCodeDarkThemeJSON),
      mapExtension: {
        rtlola:"rtlola",
        lola:"rtlola",
      }
    },
    {
      id: "rtlola",
      scopeName: 'source.rtlola',
      // @ts-ignore
      grammar: <IRawGrammar>grammarJSON,
      aliases: ['RTLola', 'rtlola'],
    }),
```

**Comment by valterkraemer** [comment]
I haven't ever added a new language, but I think this should work! ☺️

```ts
syntaxHighlight({
  theme: "code-dark",
  mapExtension: {
    rtlola: "rtlola",
    lola: "rtlola",
  },
  langs: [{
    id: "rtlola",
    scopeName: 'source.rtlola',
    grammar: grammarJSON,
    aliases: ['RTLola', 'rtlola'],
  }]
})
```

**Comment by valterkraemer** [comment]
Don't want to re-export any types. But I should evaluate if I should move `shiki` from `dependencies` to `peerDependencies` instead, and let everybody install `shiki` separately.
